### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.core.exceptions.ODataV4Error
  fullName: azure.core.exceptions.ODataV4Error
  inheritance:
  - inheritance:
    - inheritance:
      - inheritance:
        - inheritance:
          - type: builtins.object
          type: builtins.BaseException
        type: builtins.Exception
      type: azure.core.exceptions.AzureError
    type: azure.core.exceptions.HttpResponseError
  langs:
  - python
  module: azure.core.exceptions
  name: ODataV4Error
  summary: 'An HTTP response error where the JSON is decoded as OData V4 error format.


    [http://docs.oasis-open.org/odata/odata-json-format/v4.0/os/odata-json-format-v4.0-os.html#_Toc372793091](http://docs.oasis-open.org/odata/odata-json-format/v4.0/os/odata-json-format-v4.0-os.html#_Toc372793091)'
  syntax:
    content: ODataV4Error(response, **kwargs)
    variables:
    - description: The parsed JSON body as attribute for convenience.
      id: odata_json
      type:
      - dict
    - description: 'Its value is a service-defined error code.

        This code serves as a sub-status for the HTTP error code specified in the
        response.'
      id: code
      type:
      - str
    - description: Human-readable, language-dependent representation of the error.
      id: message
      type:
      - str
    - description: 'The target of the particular error (for example, the name of the
        property in error).

        This field is optional and may be None.'
      id: target
      type:
      - str
    - description: 'Array of ODataV4Format instances that MUST contain name/value
        pairs

        for code and message, and MAY contain a name/value pair for target, as described
        above.'
      id: details
      type:
      - list[ODataV4Format]
    - description: 'An object. The contents of this object are service-defined.

        Usually this object contains information that will help debug the service.'
      id: innererror
      type:
      - dict
  type: class
  uid: azure.core.exceptions.ODataV4Error
references:
- fullName: list[ODataV4Format]
  name: list[ODataV4Format]
  spec.python:
  - fullName: list
    name: list
    uid: list
  - fullName: '['
    name: '['
  - fullName: ODataV4Format
    name: ODataV4Format
    uid: ODataV4Format
  - fullName: ']'
    name: ']'
  uid: list[ODataV4Format]
